version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: parking-control-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: parking-control
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:
    driver: bridge
